### ISSUE TITLE
About the results of fbcnn_color.pth 

### ISSUE THREAD

**Issue by YangGangZhiQi** [jiaxi-jiang/FBCNN#3]
Hi,
    Great works! I test your model(fbcnn_color.pth) in 'testset/Real' dataset. The results are not so remarkable as the picture in this master.  The output of model(fbcnn_color.pth) without qf_input are as follow(left is input, right is output): 
   
![merge_1](https://user-images.githubusercontent.com/87355944/134884504-e8c1b7d7-a272-4b21-bd37-1862fc972e42.jpg)
![Uploading merge_2.jpg…]()
![merge_3](https://user-images.githubusercontent.com/87355944/134884577-154964a7-8ab5-4e12-88c5-b6cd4a88a6c6.jpg)

![merge_4](https://user-images.githubusercontent.com/87355944/134884607-ff4d0e95-d622-4f3f-86ab-08d1f7e7b0d7.jpg)
![merge_5](https://user-images.githubusercontent.com/87355944/134884656-f1dc4611-e4ba-4e28-84b7-38aa716e6dcf.jpg)
![merge_6](https://user-images.githubusercontent.com/87355944/134884666-f3db5896-0d83-4832-b7bc-c4576b840cf8.jpg)
I don't kown if there are something wrong with my results.  And the output of model(fbcnn_color.pth) with qf_input are also not so good. When zoom out, I can find  obvious artifacts. Hope for your reply.

**Comment by jiaxi-jiang** [comment]
Hi, thanks for your interest!

The provided color model is trained with the single JPEG degradation model. As we analyze in the paper, such blind models can not deal well with real JPEG images which are compressed multiple times. But since FBCNN is a flexible model, to get the desirable results with less artifacts, just set qf_input as a smaller number, e.g. 10. See https://github.com/jiaxi-jiang/FBCNN/blob/main/main_test_fbcnn_color_real.py#L23

BTW, to get the desired result automatically, you can either estimate the dominant smaller quality factor using the method proposed in our paper, or augment the training data with our proposed double JPEG degradation model.

**Comment by YangGangZhiQi** [comment]
Hi，
    Thinks for your quick reply. I set qf_input=10, the results of bcnn_color.pth in 'testset/Real' dataset  are as follow.(left is input, right is output with qf_input=10)
![merge_1](https://user-images.githubusercontent.com/87355944/135006699-b0a124e3-a97d-485d-a57c-fa9368f5b96c.jpg)
![merge_2](https://user-images.githubusercontent.com/87355944/135006709-8010f3c7-4c36-430e-a7c1-6f99e3883795.jpg)

![merge_3](https://user-images.githubusercontent.com/87355944/135006714-03ef2e26-e81d-4e6c-abbc-eeb7ca4220b1.jpg)
![merge_4](https://user-images.githubusercontent.com/87355944/135006721-71d1390f-0bd1-4dd5-9fd2-4a93a52d35a4.jpg)
![merge_5](https://user-images.githubusercontent.com/87355944/135006729-7bbdad61-7955-4fcf-ad63-ee252728e6d6.jpg)
![merge_6](https://user-images.githubusercontent.com/87355944/135006734-33de9137-71f3-44e7-b7c1-7f5e34615c9a.jpg)

There are also not so good as you show in this master. When zoom in, I can find obvious artifacts. I guess the pictures you show in this master are not the same with 'testset/Real'. Is that right?

**Comment by jiaxi-jiang** [comment]
The pictures I show are exactly the same as 'test/Real'. Just directly run `main_test_fbcnn_color_real.py` then you can get the result. Please note that the quality factor [0,100] is transformed to [1,0] as the input of the network. So quality factor 10 corresponds to 0.9 as the input parameter.
https://github.com/jiaxi-jiang/FBCNN/blob/main/main_test_fbcnn_color_real.py#L87
Let me know if you still can not the same result.

**Comment by YangGangZhiQi** [comment]
The pictures upload above is just the results of main_test_fbcnn_color_real.py. Below is the runnung log.
[Real_fbcnn_color.log](https://github.com/jiaxi-jiang/FBCNN/files/7243277/Real_fbcnn_color.log)

![result_pic](https://user-images.githubusercontent.com/87355944/135074171-89b4f788-bc16-48ee-898e-5a73216e534c.png)
@jiaxi-jiang I think the output pictures are not so good  as you show in this master.  I don't kown whether there is some thing wrong.

**Comment by jiaxi-jiang** [comment]
Could you attach the original restored images with qf_10 and qf_5 for image 1-4, and qf_70 for image 5 and 6?

**Comment by YangGangZhiQi** [comment]
I could not get useful information from you, just upload again, again and again. This is useless! I will close this issue. The effectiveness of FBCNN model(fbcnn_color.pth) remains to be unlear.

**Comment by jiaxi-jiang** [comment]
I don't know your aim of coming here. The images I show in this repo is super easy to get from the provided codes, pre-trained model and test images. Malicious comments are not welcome.

#### Fig.1 with input qf_control = 10
![1_qf_10](https://user-images.githubusercontent.com/26936848/135214122-3053a360-1213-4a1c-b9c7-e18342473998.png)

#### Fig. 2 with input qf_control = 5
![2_qf_5](https://user-images.githubusercontent.com/26936848/135214391-afccda52-1f57-4b2a-a0dd-1017015cde91.png)
 
#### Fig. 3 with input qf_control = 10
![3_qf_10](https://user-images.githubusercontent.com/26936848/135214572-7a804e68-7f21-4023-95f9-a6bc1fbae4d7.png)

#### Fig. 4 with input qf_control =10
![4_qf_10](https://user-images.githubusercontent.com/26936848/135214634-92d1dade-34a0-4549-8423-cc056ae5217c.png)

#### Fig. 5 with input qf_control = 70
![5_qf_70](https://user-images.githubusercontent.com/26936848/135214770-50fc2fd3-ca3c-45ef-8e98-6d75ddb35015.png)

#### Fig. 6 with input qf_control = 70
![6_qf_70](https://user-images.githubusercontent.com/26936848/135214800-e64ae810-3a55-4bd1-8582-8b1e05ad2d1a.png)

#### log file
[Real_fbcnn_color.log](https://github.com/jiaxi-jiang/FBCNN/files/7249371/Real_fbcnn_color.log)

**Comment by YangGangZhiQi** [comment]
Sorry for my unpatient comment. I just could not understand the big difference between our results with the same inputs\code\model。From your upload pictures and log file, I find the predicted quality factors of the model match, just output pictures are not so good as yours. I guess maybe the model we use is different. I would appreciate it if you could reupload your model(fbcnn_color.pth). No meaning to bother anyone.

**Comment by jiaxi-jiang** [comment]
I just download my repo from a new machine and run the code, without changing anything. The models and test images are both exactly the same. The results you show with many artifacts seem that the qf_control is a large number e.g. 90. So I am interested to see your results with qf_control = 5 or 10 because in this case most artifacts together with some texture details should be removed.

**Comment by cszn** [comment]
Just run the code [main_test_fbcnn_color_real.py](https://github.com/jiaxi-jiang/FBCNN/blob/main/main_test_fbcnn_color_real.py). 


```
python main_test_fbcnn_color_real.py
```

**Comment by YangGangZhiQi** [comment]
@jiaxi-jiang @cszn When running the model with cpu mode, I can get the same results with yours. But with gpu mode, the output pictures of model with qf_control = [5,10, 30, 50, 70, 90] are same.  I print the  values of qf_embedding in FBCNN network with qf_control=[5,10,50, 70, 90], there are same too. It's really weird  that the outputs become different with different device(cpu/gpu).
