### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by YassineYousfi** [jiaxi-jiang/FBCNN#6]
Hi,

The README says that code will be released here https://github.com/cszn/KAIR/

Any idea when?

Thanks!

**Comment by fennudehaogua** [comment]
Same question，can you provide training code？

**Comment by jiaxi-jiang** [comment]
Hi, sorry for the late response, as I am a little bit busy recently. We will release the training codes soon.

**Comment by jiaxi-jiang** [comment]
Sorry for the long wait. The training code is available now, welcome to check out:)
