### ISSUE TITLE
About the result  under rgb2ycbcr of opencv version

### ISSUE THREAD

**Issue by JuZiSYJ** [jiaxi-jiang/FBCNN#7]
Hi, I test the result on classic5 and live1   in **gray** with pre-trained weight

However, I find some mistakes caused by **rgb2ycbcr** function

Here is my  offline test result
![image](https://user-images.githubusercontent.com/38501523/147210835-4491ed4a-8867-4b3f-81b7-d9cc75d32f34.png)

where classic5 is ok because it is gray input, and the **live1 result** is strange because of the **rgb2ycbcr**  function. 

The GT I compare is produced by **Matlab** version YCbCr, which is different from  **OpenCV** version which is utilized in your training and eval process.
`            if n_channels == 3:
             img_L = cv2.cvtColor(img_L, cv2.COLOR_RGB2BGR)                
            _, encimg = cv2.imencode('.jpg', img_L, [int(cv2.IMWRITE_JPEG_QUALITY), quality_factor])
            img_L = cv2.imdecode(encimg, 0) if n_channels == 1 else cv2.imdecode(encimg, 3)`

The logging result in live1_qf10 is
`21-12-23 15:43:59.031 : Average PSNR/SSIM/PSNRB - live1_fbcnn_gray_10 -: 28.96$\vert$0.8254$\vert$28.64.`
which is a little higher than 26.97 but much lower than 29.75, because the model is for OpenCV version Y, not Matlab version

However, the common setting in deblocking is using Matlab version Y

I test ICCV21-Learning Dual Priors for JPEG Compression Artifacts Removal, the offline results are
![image](https://user-images.githubusercontent.com/38501523/147212311-8f5bca24-97e6-4c8f-b192-f1e635906445.png)

It is similar to the results produced in paper

I hope it may be helpful.

**Comment by jiaxi-jiang** [comment]
Hi, thanks for the proposed issue. The provided testset ```LIVE1_gray``` is Matlab Y channel. If I run the code ```main_test_fbcnn_gray.py``` to test on these images, the psnr result for quality factor 10 is 29.75. Did you do the same or?

**Comment by JuZiSYJ** [comment]
I test it with LIVE image in **RGB** format, which will be extracted through  opencv encoder (cv2.imread(path, 0))
![image](https://user-images.githubusercontent.com/38501523/147402741-151bd2f1-669e-4533-911f-db7b8ebb6adb.png)

I got the **same** results using LIVE1_gray. Maybe there is a mistake in  test_gray.py  when the input image is in RGB format.
