### ISSUE TITLE
Real data testing

### ISSUE THREAD

**Issue by yiyunchen** [jiaxi-jiang/FBCNN#8]
hello, it seems the results of the real dataset are not run from the fbcnn_color.pth ? Would you mind providing the corresponding fbcnn model for the real dataset?
Thank you!

**Comment by jiaxi-jiang** [comment]
Hi, the real examples I showed are run from the ```fbcnn_color.pth```. What results did you get?

**Comment by yiyunchen** [comment]
![4](https://user-images.githubusercontent.com/32478395/148313597-29596cdf-4e3e-4ccc-aa2e-1ddb5f38d2b5.png)

**Comment by jiaxi-jiang** [comment]
It looks like the default result from the model trained with single jpeg images. Please check out the result with given QF = 10. https://github.com/jiaxi-jiang/FBCNN/blob/main/main_test_fbcnn_color_real.py#L23
